__Exploratory Data Analysis (EDA)__

- Inspect distributions, missing values, outliers.
- Plot time series of IV, skew, curvature.
- Compare SPY vs QQQ.
- Correlation checks.
- Document findings.

In [1]:
# import parquet_extractor  
# import importlib

# importlib.reload(parquet_extractor)

In [2]:
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import polars as pl
import numpy as np
import statsmodels.api as sm
from statsmodels.tsa.stattools import adfuller
from parquet_extractor import load_ticker_year_data, get_ticker_metadata

__Load the filtered parquet__

In [3]:
# metadata = get_ticker_metadata('SPY', Path("."))
# metadata

In [4]:
def load_merged_ticker_data(tickers, start_year, end_year, data_dir=Path(".")):
    """Load and merge data for multiple tickers across a range of years."""
    all_data = []

    if isinstance(tickers, str):
        tickers = [tickers]

    for ticker in tickers:
        for year in range(start_year, end_year + 1):
            try:
                df = load_ticker_year_data(ticker, year, data_dir)
                df = df.with_columns([
                    pl.lit(ticker).alias("ticker"),
                ])
                all_data.append(df)
            except FileNotFoundError:
                print(f"Data not found for {ticker} in {year}, skipping.")
            except Exception as e:
                print(f"Error loading {ticker} in {year}: {e}")

    if all_data:
        return pl.concat(all_data)
    else:
        return pl.DataFrame()

In [5]:
spy_pl = load_merged_ticker_data('SPY', 2005, 2023, Path("."))
spy_df = spy_pl.to_pandas()
spy_df.sample(7)

,date,secid,symbol,cp_flag,exdate,strike_price,best_bid,best_offer,volume,open_interest,...,price_diff_5d,price_diff_8d,price_diff_13d,price_diff_21d,price_diff_34d,price_diff_55d,price_diff_89d,price_diff_144d,price_diff_233d,ticker
16812619,2020-12-29,109820.0,SPY 210319P380000,P,2021-03-19,380000.0,17.96,18.03,187.0,40630.0,...,0.00000,0.00000,2.45999,2.45999,4.22000,-0.78000,1.86999,1.60998,16.13000,SPY
6751,2005-09-02,109820.0,CYY.LA,C,2006-12-16,105000.0,21.80,22.00,10.0,366.0,...,1.22000,1.22000,0.68000,-0.79000,-1.06000,-1.38000,-1.17000,1.78000,6.55000,SPY
17047606,2021-07-06,109820.0,SPY 211217P115000,P,2021-12-17,115000.0,0.10,0.11,861.0,5441.0,...,-0.79001,-0.79001,2.50000,4.86999,9.82000,8.44998,22.07000,41.44998,57.22998,SPY
19664595,2021-12-31,109820.0,SPY 220121C454000,C,2022-01-21,454000.0,22.65,22.76,49.0,4237.0,...,-1.20001,-1.20001,-1.20001,-2.52002,-1.91001,-2.30002,11.89999,4.35998,16.16998,SPY
16985007,2020-12-24,109820.0,SPY 210521C450000,C,2021-05-21,450000.0,0.27,0.30,20.0,710.0,...,0.00000,1.42999,1.76001,1.14001,-3.23999,4.34000,-1.17001,11.54001,38.79999,SPY
1400236,2009-07-20,109820.0,OBM.XE,P,2011-12-17,25000.0,0.30,0.35,31.0,24683.0,...,1.00100,1.00100,1.87100,5.02900,6.96100,3.18100,3.09100,4.62100,7.74100,SPY
17325214,2021-05-17,109820.0,SPY 211217P290000,P,2021-12-17,290000.0,3.70,3.80,1.0,4033.0,...,-1.06000,-1.06000,5.23999,10.10999,1.31000,-6.60001,-1.78000,3.34998,14.91000,SPY

In [6]:
# Save to Parquet
spy_pl.write_parquet("./parquet/spy_historical_2005_2023_v1.parquet")

In [8]:
df = pl.read_parquet("./parquet/spy_historical_2005_2023_v1.parquet")
print(df.shape)
# print(df.head()

(24914760, 37)

In [10]:
df.sample(20)

shape: (20, 37)
┌────────────┬──────────┬────────────┬─────────┬───┬────────────┬────────────┬────────────┬────────┐
│ date       ┆ secid    ┆ symbol     ┆ cp_flag ┆ … ┆ price_diff ┆ price_diff ┆ price_diff ┆ ticker │
│ ---        ┆ ---      ┆ ---        ┆ ---     ┆   ┆ _89d       ┆ _144d      ┆ _233d      ┆ ---    │
│ date       ┆ f64      ┆ str        ┆ str     ┆   ┆ ---        ┆ ---        ┆ ---        ┆ str    │
│            ┆          ┆            ┆         ┆   ┆ f64        ┆ f64        ┆ f64        ┆        │
╞════════════╪══════════╪════════════╪═════════╪═══╪════════════╪════════════╪════════════╪════════╡
│ 2008-05-14 ┆ 109820.0 ┆ JBG.FT     ┆ C       ┆ … ┆ 1.14       ┆ 3.91999    ┆ 5.91999    ┆ SPY    │
│ 2010-12-17 ┆ 109820.0 ┆ SPY 101231 ┆ P       ┆ … ┆ 1.47       ┆ 3.29       ┆ 4.01       ┆ SPY    │
│            ┆          ┆ P119000    ┆         ┆   ┆            ┆            ┆            ┆        │
│ 2021-11-26 ┆ 109820.0 ┆ SPY 211129 ┆ C       ┆ … ┆ -10.31     ┆ -4.65      ┆ 0.64999    ┆ SPY    │
│            ┆          ┆ C446000    ┆         ┆   ┆            ┆            ┆            ┆        │
│ 2021-06-09 ┆ 109820.0 ┆ SPY 210630 ┆ C       ┆ … ┆ 2.57998    ┆ 9.70999    ┆ 6.02999    ┆ SPY    │
│            ┆          ┆ C383000    ┆         ┆   ┆            ┆            ┆            ┆        │
│ 2011-03-07 ┆ 109820.0 ┆ SPY 110319 ┆ C       ┆ … ┆ 0.5        ┆ -2.42002   ┆ -1.14002   ┆ SPY    │
│            ┆          ┆ C120000    ┆         ┆   ┆            ┆            ┆            ┆        │
│ …          ┆ …        ┆ …          ┆ …       ┆ … ┆ …          ┆ …          ┆ …          ┆ …      │
│ 2015-02-05 ┆ 109820.0 ┆ SPY 150417 ┆ C       ┆ … ┆ 3.37999    ┆ 3.04       ┆ 3.47001    ┆ SPY    │
│            ┆          ┆ C207000    ┆         ┆   ┆            ┆            ┆            ┆        │
│ 2020-07-02 ┆ 109820.0 ┆ SPY 220121 ┆ P       ┆ … ┆ -7.10999   ┆ 9.26001    ┆ 30.63      ┆ SPY    │
│            ┆          ┆ P270000    ┆         ┆   ┆            ┆            ┆            ┆        │
│ 2020-04-14 ┆ 109820.0 ┆ SPY 200515 ┆ C       ┆ … ┆ 14.47      ┆ -16.44998  ┆ -48.41     ┆ SPY    │
│            ┆          ┆ C390000    ┆         ┆   ┆            ┆            ┆            ┆        │
│ 2020-03-10 ┆ 109820.0 ┆ SPY 200331 ┆ P       ┆ … ┆ -7.84      ┆ -48.53     ┆ -43.78     ┆ SPY    │
│            ┆          ┆ P325000    ┆         ┆   ┆            ┆            ┆            ┆        │
│ 2020-10-13 ┆ 109820.0 ┆ SPY 210917 ┆ C       ┆ … ┆ 10.36999   ┆ 21.39999   ┆ 9.95999    ┆ SPY    │
│            ┆          ┆ C340000    ┆         ┆   ┆            ┆            ┆            ┆        │
└────────────┴──────────┴────────────┴─────────┴───┴────────────┴────────────┴────────────┴────────┘